# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39b7a96b4fb843e6bd750c99d5fa539c89312beed35e7b7d1d9fe0db9bbaee0317bb76ddb2e1528280b2987f9cfdaf9da182990c4012f08d1fa15d109003d898

test:
  secret_key_base: fbfc5688a31993f5a8dd7d6fead9a45f88a7d86498e200cadb9a6a86267463b5d3124a6679c84633ed1475c4c1f7a062b00e271489491d0ea1b76482eca0c5c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
